# Use the official Node.js 18 image
# https://hub.docker.com/_/node
FROM node:18-alpine

# Create and change to the app directory
WORKDIR /app

# Copy application files
COPY . ./

# Install dependencies
RUN npm install

# Expose port
EXPOSE 8080

# Run the application
CMD ["npm", "start"]